// Generate fr.json from en.json with French translations
const fs = require('fs');
const path = require('path');

const en = JSON.parse(fs.readFileSync(path.join(__dirname, '../client/i18n/locales/en.json'), 'utf8'));

// Direct value translations
const t = {
    // Tabs
    "Qibla": "Qibla", "Prayer": "Prière", "Quran": "Coran", "Azkar": "Azkar", "Settings": "Paramètres",
    // Settings
    "Appearance": "Apparence", "Customize your theme": "Personnalisez votre thème",
    "Language": "Langue", "Choose your language": "Choisissez votre langue",
    "Prayer & Fasting": "Prière et Jeûne",
    "Notifications, azan, and reminders": "Notifications, azan et rappels",
    "Storage & Downloads": "Stockage et Téléchargements",
    "Manage offline content": "Gérer le contenu hors ligne",
    "Word by Word": "Mot à Mot", "Translation language": "Langue de traduction",
    "Dhikr Reminders": "Rappels de Dhikr", "Floating overlay reminders": "Rappels en superposition flottante",
    "Feedback & Suggestions": "Commentaires et Suggestions",
    "Help us improve the app": "Aidez-nous à améliorer l'application",
    "Color Mode": "Mode de couleur", "Theme": "Thème",
    "Light": "Clair", "Dark": "Sombre", "Auto": "Auto",
    // Prayer
    "Prayer Times": "Horaires de Prière",
    "Fajr": "Fajr", "Sunrise": "Lever du soleil", "Dhuhr": "Dhuhr",
    "Asr": "Asr", "Maghrib": "Maghrib", "Isha": "Isha",
    "NEXT PRAYER": "PROCHAINE PRIÈRE", "Time Remaining": "Temps Restant",
    "Prayer Calendar": "Calendrier de Prière", "Prayer Stats": "Statistiques de Prière",
    "Progress": "Progrès", "Hijri Calendar": "Calendrier Hégirien",
    "Calculation Method": "Méthode de Calcul",
    "Prayed": "Prié", "Missed": "Manqué", "Late": "En retard",
    "On Time": "À l'heure", "Not logged": "Non enregistré", "Log Prayer": "Enregistrer la Prière",
    "Current Streak": "Série Actuelle", "DAYS": "JOURS", "DAY": "JOUR",
    "Today": "Aujourd'hui", "Yesterday": "Hier",
    "Location": "Localisation", "Set your location": "Définir votre emplacement",
    "Tap to set your location for accurate prayer times": "Appuyez pour définir votre emplacement pour des horaires de prière précis",
    "No Location Set": "Aucun emplacement défini",
    "Checking location permission...": "Vérification de la permission de localisation...",
    "Location Access Required": "Accès à la localisation requis",
    "We need your location to calculate accurate prayer times for your area.": "Nous avons besoin de votre localisation pour calculer des horaires de prière précis pour votre zone.",
    "Please enable location in your browser settings.": "Veuillez activer la localisation dans les paramètres de votre navigateur.",
    "Enable Location": "Activer la localisation", "Open Settings": "Ouvrir les paramètres",
    "Loading prayer times...": "Chargement des horaires de prière...",
    "Failed to load prayer times": "Échec du chargement des horaires de prière",
    "HOURS": "HEURES", "MINUTES": "MINUTES", "SECONDS": "SECONDES", "min": "min",
    // Qibla
    "Direction": "Direction", "degrees": "degrés", "Compass": "Boussole",
    "Distance": "Distance", "to Kaaba": "vers la Kaaba",
    "Facing Qibla": "Face à la Qibla", "Turn Left": "Tournez à gauche", "Turn Right": "Tournez à droite",
    "Direction Locked": "Direction verrouillée", "Tap to Unlock": "Appuyez pour déverrouiller",
    "Lock Direction": "Verrouiller la direction",
    "Compass not available": "Boussole non disponible",
    "Compass not available on web. Use on mobile device.": "Boussole non disponible sur le web. Utilisez un appareil mobile.",
    "Calibrate your compass by moving your phone in a figure-8 pattern": "Calibrez votre boussole en déplaçant votre téléphone en forme de 8",
    "Move phone in figure-8 to calibrate": "Déplacez le téléphone en forme de 8 pour calibrer",
    "HEADING": "CAP", "QIBLA": "QIBLA", "KM": "KM",
    "Mosques": "Mosquées", "Getting your location...": "Obtention de votre localisation...",
    "Initializing compass...": "Initialisation de la boussole...",
    "We need your location to calculate the Qibla direction from your current position.": "Nous avons besoin de votre localisation pour calculer la direction de la Qibla depuis votre position actuelle.",
    // Quran
    "Surah": "Sourate", "Juz": "Juz", "Page": "Page", "Verse": "Verset", "Verses": "Versets",
    "Search": "Rechercher", "Search Quran": "Rechercher dans le Coran",
    "Bookmark": "Signet", "Bookmarks": "Signets", "Bookmarked": "Marqué",
    "Add Note": "Ajouter une note", "Notes": "Notes",
    "Highlight": "Surligner", "Highlights": "Surlignages",
    "Copy": "Copier", "Share": "Partager",
    "Play": "Lire", "Pause": "Pause", "Stop": "Arrêter", "Continue": "Continuer",
    "Tafsir": "Tafsir", "Translation": "Traduction", "Translations": "Traductions",
    "Transliteration": "Translittération", "Reciter": "Récitateur",
    "Last Read": "Dernière lecture", "Continue where you left off": "Continuer où vous en étiez",
    "Meccan": "Mecquoise", "Medinan": "Médinoise",
    "Save": "Enregistrer", "Delete": "Supprimer", "Cancel": "Annuler",
    "Saved Verses": "Versets enregistrés", "All": "Tout", "Recent": "Récent",
    "Tafsir & Translations": "Tafsir et Traductions",
    "Download": "Télécharger", "Downloaded": "Téléchargé", "Downloading": "Téléchargement",
    "Read Mode": "Mode lecture", "Mushaf Mode": "Mode Mushaf",
    "Surah Reader": "Lecteur de Sourate",
    "Go to page": "Aller à la page", "Go to Surah": "Aller à la Sourate", "Go to Juz": "Aller au Juz",
    "Audio": "Audio",
    // Azkar
    "Azkar & Duas": "Azkar et Douas", "Morning Azkar": "Azkar du matin", "Evening Azkar": "Azkar du soir",
    "After Prayer": "Après la prière", "Sleep": "Sommeil", "Wake Up": "Réveil",
    "Daily Tip": "Conseil du jour", "Categories": "Catégories", "Duas": "Douas", "Guides": "Guides",
    "Favorites": "Favoris", "Count": "Compteur", "Completed": "Terminé",
    "Repeat": "Répéter", "times": "fois", "time": "fois", "remaining": "restant",
    "Reset": "Réinitialiser", "Dua of the Day": "Doua du jour",
    "Daily Dhikr": "Dhikr quotidien", "Dhikr Goal": "Objectif de Dhikr",
    "Worship & Prayer": "Adoration et Prière", "Daily Life": "Vie quotidienne",
    "Travel": "Voyage", "Food & Drink": "Nourriture et Boisson",
    "Protection": "Protection", "Hadith": "Hadith", "Islamic Guides": "Guides Islamiques",
    "Search azkar & duas...": "Rechercher azkar et douas...",
    "Search duas...": "Rechercher des douas...",
    "Quranic": "Coranique", "Prophetic": "Prophétique", "Custom": "Personnalisé",
    "Custom Duas": "Douas personnalisées", "Add Custom Dua": "Ajouter une doua personnalisée",
    "No custom duas yet": "Pas encore de douas personnalisées",
    "No favorites yet": "Pas encore de favoris",
    "No results found": "Aucun résultat trouvé",
    "Are you sure you want to delete this dua?": "Êtes-vous sûr de vouloir supprimer cette doua ?",
    "Tap to start": "Appuyez pour commencer", "Target": "Objectif",
    "All Categories": "Toutes les catégories", "Delete Dua": "Supprimer la doua",
    "My Duas": "Mes Douas", "result": "résultat", "results": "résultats",
    "No duas found for": "Aucune doua trouvée pour",
    "Search guides...": "Rechercher des guides...",
    "No guides found for": "Aucun guide trouvé pour", "Back": "Retour",
    "No custom duas yet.\nAdd your personal supplications.": "Pas encore de douas personnalisées.\nAjoutez vos invocations personnelles.",
    "No favorite duas yet.\nTap the heart icon on any dua.": "Pas encore de douas favorites.\nAppuyez sur l'icône cœur de n'importe quelle doua.",
    "No Quranic duas available": "Aucune doua coranique disponible",
    "No Prophetic duas available": "Aucune doua prophétique disponible",
    "adhkar": "adhkar",
    // Progress
    "Reading Progress": "Progrès de lecture", "Overall Progress": "Progrès global",
    "Complete": "Terminé", "Pages Read": "Pages lues", "Juz Complete": "Juz terminés",
    "Khatm": "Khatm", "Today's Progress": "Progrès d'aujourd'hui",
    "verses read": "versets lus", "pages read": "pages lues",
    "Reading Streak": "Série de lecture", "Longest Streak": "Plus longue série",
    "Best Streak": "Meilleure série", "This Week": "Cette semaine",
    "Average": "Moyenne", "pages/day": "pages/jour",
    "Daily Goal Settings": "Paramètres de l'objectif quotidien",
    "Enable Daily Goal": "Activer l'objectif quotidien",
    "Goal Type": "Type d'objectif", "Pages": "Pages",
    "Save Goal": "Enregistrer l'objectif",
    "Reading Reminder": "Rappel de lecture", "Enable Reminder": "Activer le rappel",
    "Reminder Time": "Heure du rappel",
    "Reset All Progress": "Réinitialiser tout le progrès",
    "Are you sure you want to reset all reading progress? This cannot be undone.": "Êtes-vous sûr de vouloir réinitialiser tout le progrès de lecture ? Cette action est irréversible.",
    "No daily goal set": "Aucun objectif quotidien défini",
    "Invalid Goal": "Objectif invalide",
    "Please enter a valid number": "Veuillez entrer un nombre valide",
    "goal must be between": "l'objectif doit être entre", "and": "et",
    "Permission Required": "Permission requise",
    "Please enable notifications in your device settings to use reading reminders.": "Veuillez activer les notifications dans les paramètres de votre appareil pour utiliser les rappels de lecture.",
    "Failed to save goal settings": "Échec de l'enregistrement des paramètres d'objectif",
    "Failed to reset progress": "Échec de la réinitialisation du progrès",
    "Loading progress...": "Chargement du progrès...", "Done": "Terminé", "Goal": "Objectif",
    "Weekly Overview": "Aperçu hebdomadaire", "Monthly Overview": "Aperçu mensuel",
    "Streak": "Série", "Total Prayers": "Total des prières",
    "Completion Rate": "Taux d'achèvement", "Prayer Log": "Journal de prière",
    "Weekly": "Hebdomadaire", "Monthly": "Mensuel", "All Time": "Tout le temps",
    "Export Stats": "Exporter les statistiques",
    "Qada Tracker": "Suivi des Qada", "Qada Remaining": "Qada restants",
    "Taraweeh": "Tarawih", "Charity": "Charité",
    "Zakat Calculator": "Calculateur de Zakat",
    "Hifz Progress": "Progrès de Hifz", "Quran Schedule": "Programme du Coran",
    // Notifications
    "Notification Settings": "Paramètres de notification",
    "Prayer Notifications": "Notifications de prière",
    "Get notified when it's time to pray": "Soyez notifié quand c'est l'heure de prier",
    "Prayer Alarms": "Alarmes de prière", "Azan Settings": "Paramètres de l'Azan",
    "Azan": "Azan", "Azan Sound": "Son de l'Azan",
    "Play \"Haya Al Salat\" before prayer": "Jouer \"Haya Al Salat\" avant la prière",
    "Silent Mode": "Mode silencieux", "Flip to Silence": "Retourner pour couper le son",
    "Flip your phone face-down to silence the azan": "Retournez votre téléphone face vers le bas pour couper l'azan",
    "Test Azan": "Tester l'Azan", "Vibration": "Vibration",
    "Iqama": "Iqama", "Iqama Reminder": "Rappel d'Iqama", "Iqama Wait": "Attente d'Iqama",
    "Iqama Delay": "Délai d'Iqama", "minutes after azan": "minutes après l'azan",
    "minutes": "minutes", "Enabled": "Activé", "Disabled": "Désactivé",
    "Time Adjustments": "Ajustements de temps",
    "Adjust prayer times (minutes)": "Ajuster les horaires de prière (minutes)",
    "High Latitude Rule": "Règle de haute latitude",
    "Asr Calculation": "Calcul de l'Asr", "Standard": "Standard", "Hanafi": "Hanafi",
    "Prayer Tracking": "Suivi des prières", "Enable Tracking": "Activer le suivi",
    "Track your daily prayers": "Suivez vos prières quotidiennes",
    "Missed Prayer Reminder": "Rappel de prière manquée",
    "Remind after prayer time passes": "Rappeler après le passage de l'heure de prière",
    "Reminder Delay": "Délai de rappel", "minutes after prayer": "minutes après la prière",
    "Fasting": "Jeûne", "Suhoor Reminder": "Rappel du Suhoor", "Iftar Reminder": "Rappel de l'Iftar",
    "minutes before Suhoor": "minutes avant le Suhoor",
    "minutes before Iftar": "minutes avant l'Iftar",
    "Fasting Reminders": "Rappels de jeûne",
    "Enable fasting reminders": "Activer les rappels de jeûne",
    "Play azan when prayer time arrives": "Jouer l'azan à l'heure de la prière",
    "Select which prayers play azan sound": "Sélectionnez les prières avec le son de l'azan",
    "Prayer Selection": "Sélection des prières",
    "Choose which prayers get iqama": "Choisissez les prières avec iqama",
    "Test Iqama": "Tester l'Iqama",
    "Iqama sound is playing now. If you don't hear it, check your volume.": "Le son de l'Iqama est en cours. Si vous ne l'entendez pas, vérifiez votre volume.",
    "Fine-tune prayer times (±30 min)": "Ajustez les horaires de prière (±30 min)",
    "Recommended": "Recommandé", "Active": "Actif", "Use Auto": "Utiliser Auto",
    "Auto-detect by location": "Détection automatique par localisation",
    "Auto-detected for": "Détecté automatiquement pour",
    // Qada Tracker
    "Total Qada prayers remaining": "Total des prières Qada restantes",
    "Tap the count number to edit directly. Use 'Log' after praying a Qada.": "Appuyez sur le nombre pour modifier directement. Utilisez 'Enregistrer' après avoir prié un Qada.",
    // Location
    "Location Settings": "Paramètres de localisation",
    "Search city...": "Rechercher une ville...",
    "Current Location": "Position actuelle", "Use Current Location": "Utiliser la position actuelle",
    "Manual Entry": "Saisie manuelle", "Latitude": "Latitude", "Longitude": "Longitude",
    "Detecting location...": "Détection de la localisation...",
    "Location saved": "Localisation enregistrée", "Invalid coordinates": "Coordonnées invalides",
    "Location unavailable": "Localisation indisponible",
    "Permission required": "Permission requise", "Manual": "Manuel",
    "LOCATION SOURCE": "SOURCE DE LOCALISATION",
    "Use GPS Location": "Utiliser la localisation GPS",
    "Set Location Manually": "Définir la localisation manuellement",
    "Search for any city worldwide": "Rechercher n'importe quelle ville dans le monde",
    "RECENT LOCATIONS": "EMPLACEMENTS RÉCENTS",
    "Your location is used to calculate accurate prayer times and Qibla direction. Manual location is useful when GPS is unavailable or inaccurate.": "Votre localisation est utilisée pour calculer des horaires de prière et la direction de la Qibla précis. La localisation manuelle est utile quand le GPS est indisponible ou imprécis.",
    // Qada
    "Total Remaining": "Total restant", "Add Missed": "Ajouter manqué",
    "Prayers Made Up": "Prières rattrapées", "Remaining": "Restant",
    "Long press on a prayer count to subtract": "Appui long sur un compteur de prière pour soustraire",
    "No Qada prayers remaining. MashaAllah!": "Aucune prière Qada restante. MashaAllah !",
    "prayers": "prières",
    // Zakat
    "Total Wealth": "Patrimoine total", "Enter total wealth amount": "Entrez le montant total du patrimoine",
    "Calculate": "Calculer", "Zakat Due": "Zakat due", "Nisab": "Nisab",
    "Meets Nisab threshold": "Atteint le seuil du Nisab",
    "Does not meet Nisab threshold": "N'atteint pas le seuil du Nisab",
    "Gold Nisab": "Nisab d'or", "Silver Nisab": "Nisab d'argent",
    "Zakat is 2.5% of your total qualifying wealth held for one lunar year.": "La Zakat est de 2,5% de votre patrimoine éligible détenu pendant une année lunaire.",
    "Gold": "Or", "Silver": "Argent", "Cash & Bank Balances": "Liquide et soldes bancaires",
    "Stocks & Investments": "Actions et investissements", "Rental Property": "Propriété locative",
    "Total Assets": "Total des actifs", "Zakat Payable": "Zakat à payer", "Currency": "Devise",
    // Charity
    "Charity Tracker": "Suivi des dons", "Total Donated": "Total donné",
    "Add Donation": "Ajouter un don", "Set Goal": "Définir un objectif",
    "Recent Donations": "Dons récents", "No donations yet": "Aucun don pour le moment",
    "Amount": "Montant", "Type": "Type", "Category": "Catégorie", "Date": "Date",
    "Are you sure you want to delete this donation?": "Êtes-vous sûr de vouloir supprimer ce don ?",
    "Enter amount": "Entrez le montant", "Select category": "Sélectionnez la catégorie",
    "Sadaqah": "Sadaqah", "Zakat": "Zakat", "Waqf": "Waqf", "Other": "Autre",
    "Goal Amount": "Montant de l'objectif", "Goal Progress": "Progrès de l'objectif",
    "To": "À", "Total Given": "Total donné", "Edit Goal": "Modifier l'objectif",
    "Zakat Status": "Statut de la Zakat", "Paid": "Payé",
    "Not yet paid this year": "Pas encore payé cette année",
    "Breakdown by Type": "Répartition par type",
    // Ramadan
    "Ramadan Dashboard": "Tableau de bord Ramadan", "Days Remaining": "Jours restants",
    "Fasting Today": "Jeûne aujourd'hui", "Log Taraweeh": "Enregistrer Tarawih",
    "Suhoor": "Suhoor", "Iftar": "Iftar", "Fasting Days": "Jours de jeûne",
    "Ramadan Mode": "Mode Ramadan",
    "Ramadan Mode will automatically activate during the blessed month of Ramadan.": "Le mode Ramadan s'activera automatiquement pendant le mois béni du Ramadan.",
    "Check back when Ramadan begins to access Suhoor/Iftar times, Quran reading schedules, Taraweeh tracking, and more.": "Revenez quand le Ramadan commence pour accéder aux horaires de Suhoor/Iftar, aux programmes de lecture du Coran, au suivi des Tarawih, et plus encore.",
    // Hifz
    "Memorized": "Mémorisé", "In Progress": "En cours", "Not Started": "Non commencé",
    "Total Memorized": "Total mémorisé", "Mark as Memorized": "Marquer comme mémorisé",
    "Mark as In Progress": "Marquer comme en cours", "Reset Surah": "Réinitialiser la Sourate",
    "Verses Memorized": "Versets mémorisés", "Due Today": "Dû aujourd'hui",
    "Revised Today": "Révisé aujourd'hui", "Daily Goal": "Objectif quotidien",
    "Due for Revision": "Dû pour révision", "Last": "Dernier", "Ease": "Facilité",
    "more verses due": "versets supplémentaires dus", "Status Legend": "Légende des statuts",
    "Notifications": "Notifications", "Daily Reminders": "Rappels quotidiens",
    "Get reminded to review your memorization": "Recevez un rappel pour réviser votre mémorisation",
    // Common
    "Loading...": "Chargement...", "Error": "Erreur", "Retry": "Réessayer",
    "OK": "OK", "Edit": "Modifier", "Close": "Fermer",
    "Copied!": "Copié !", "You are offline": "Vous êtes hors ligne",
    "Yes": "Oui", "No": "Non", "Confirm": "Confirmer", "Add": "Ajouter",
    "Remove": "Supprimer", "Enable": "Activer", "Disable": "Désactiver",
    "On": "Activé", "Off": "Désactivé", "your region": "votre région",
    "Go Back": "Retour", "Skip": "Passer",
    // Components
    "day streak": "jours de suite", "Perfect Day": "Journée parfaite",
    "Offline Mode": "Mode hors ligne", "Using cached data": "Utilisation des données en cache",
    "Last synced": "Dernière synchronisation",
    "Something went wrong": "Une erreur s'est produite", "Try Again": "Réessayer",
    // Streak
    "Prayer Streak": "Série de prières", "days": "jours", "day": "jour",
    "Start your streak today!": "Commencez votre série aujourd'hui !",
    "Great start! Keep it going!": "Bon début ! Continuez !",
    "You're building momentum!": "Vous prenez de l'élan !",
    "Amazing consistency!": "Constance incroyable !",
    "Incredible dedication!": "Dévouement incroyable !",
    "Mashallah! Truly inspiring!": "Mashallah ! Vraiment inspirant !",
};

// Recursively translate
function translate(obj) {
    if (typeof obj === 'string') return t[obj] !== undefined ? t[obj] : obj;
    if (Array.isArray(obj)) return obj.map(item => translate(item));
    if (typeof obj === 'object' && obj !== null) {
        const result = {};
        for (const [key, value] of Object.entries(obj)) {
            result[key] = translate(value);
        }
        return result;
    }
    return obj;
}

const fr = translate(en);
fs.writeFileSync(
    path.join(__dirname, '../client/i18n/locales/fr.json'),
    JSON.stringify(fr, null, 4),
    'utf8'
);
console.log('Generated fr.json');
console.log('Total keys in en:', JSON.stringify(en).split('":').length);
