import { Platform } from "react-native";
import type { ThemeConfig, ThemeColors, ThemeId } from "@/types/theme";

// Legacy export for backward compatibility
export const Colors = {
  light: {
    text: "#1F2937",
    textSecondary: "#6B7280",
    buttonText: "#FFFFFF",
    tabIconDefault: "#6B7280",
    tabIconSelected: "#059669",
    link: "#059669",
    backgroundRoot: "#F9FAFB",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#F3F4F6",
    backgroundTertiary: "#E5E7EB",
    primary: "#059669",
    primaryLight: "#10B981",
    gold: "#D4AF37",
    goldLight: "#F5E6B3",
    success: "#10B981",
    muted: "#9CA3AF",
    border: "#E5E7EB",
    cardBackground: "#FFFFFF",
    prayerActive: "#059669",
    prayerPast: "#9CA3AF",
  },
  dark: {
    text: "#ECEDEE",
    textSecondary: "#9CA3AF",
    buttonText: "#FFFFFF",
    tabIconDefault: "#6B7280",
    tabIconSelected: "#10B981",
    link: "#10B981",
    backgroundRoot: "#111827",
    backgroundDefault: "#1F2937",
    backgroundSecondary: "#374151",
    backgroundTertiary: "#4B5563",
    primary: "#10B981",
    primaryLight: "#34D399",
    gold: "#D4AF37",
    goldLight: "#B8963E",
    success: "#10B981",
    muted: "#6B7280",
    border: "#374151",
    cardBackground: "#1F2937",
    prayerActive: "#10B981",
    prayerPast: "#6B7280",
  },
};

// Theme Definitions
export const Themes: Record<ThemeId, ThemeConfig> = {
  default: {
    id: "default",
    name: "Emerald",
    nameAr: "زمردي",
    description: "Classic Islamic green theme",
    previewColors: ["#059669", "#D4AF37", "#F9FAFB"],
    light: Colors.light,
    dark: Colors.dark,
  },

  roseGold: {
    id: "roseGold",
    name: "Rose Gold",
    nameAr: "وردي ذهبي",
    description: "Soft, warm feminine aesthetic",
    previewColors: ["#D4A5A5", "#C9A86C", "#FFF5F5"],
    light: {
      text: "#5C4A4A",
      textSecondary: "#8B7575",
      buttonText: "#FFFFFF",
      tabIconDefault: "#8B7575",
      tabIconSelected: "#D4A5A5",
      link: "#D4A5A5",
      backgroundRoot: "#FFF5F5",
      backgroundDefault: "#FFFFFF",
      backgroundSecondary: "#FDF0F0",
      backgroundTertiary: "#F5E0E0",
      primary: "#D4A5A5",
      primaryLight: "#E8B4B8",
      gold: "#C9A86C",
      goldLight: "#E8D4B0",
      success: "#D4A5A5",
      muted: "#B8A0A0",
      border: "#F0D4D4",
      cardBackground: "#FFFFFF",
      prayerActive: "#D4A5A5",
      prayerPast: "#B8A0A0",
    },
    dark: {
      text: "#F5E6E8",
      textSecondary: "#C9A8AB",
      buttonText: "#FFFFFF",
      tabIconDefault: "#8B7575",
      tabIconSelected: "#E8B4B8",
      link: "#E8B4B8",
      backgroundRoot: "#2D2226",
      backgroundDefault: "#3D2F33",
      backgroundSecondary: "#4A3B3F",
      backgroundTertiary: "#5A4A4E",
      primary: "#E8B4B8",
      primaryLight: "#F0C4C8",
      gold: "#E8C896",
      goldLight: "#D4B896",
      success: "#E8B4B8",
      muted: "#8B7575",
      border: "#5A4448",
      cardBackground: "#3D2F33",
      prayerActive: "#E8B4B8",
      prayerPast: "#8B7575",
    },
  },

  lavender: {
    id: "lavender",
    name: "Lavender",
    nameAr: "لافندر",
    description: "Calming purple tones",
    previewColors: ["#9B8AA6", "#C9B896", "#FAF8FF"],
    light: {
      text: "#4A4458",
      textSecondary: "#7A7088",
      buttonText: "#FFFFFF",
      tabIconDefault: "#7A7088",
      tabIconSelected: "#9B8AA6",
      link: "#9B8AA6",
      backgroundRoot: "#FAF8FF",
      backgroundDefault: "#FFFFFF",
      backgroundSecondary: "#F5F0FA",
      backgroundTertiary: "#EBE5F2",
      primary: "#9B8AA6",
      primaryLight: "#B8A9C9",
      gold: "#C9B896",
      goldLight: "#E8DCC0",
      success: "#9B8AA6",
      muted: "#A098A8",
      border: "#E8E0F0",
      cardBackground: "#FFFFFF",
      prayerActive: "#9B8AA6",
      prayerPast: "#A098A8",
    },
    dark: {
      text: "#F0EBF5",
      textSecondary: "#A89BB8",
      buttonText: "#FFFFFF",
      tabIconDefault: "#7A7088",
      tabIconSelected: "#B8A9C9",
      link: "#B8A9C9",
      backgroundRoot: "#252030",
      backgroundDefault: "#322D40",
      backgroundSecondary: "#3E384D",
      backgroundTertiary: "#4A445A",
      primary: "#B8A9C9",
      primaryLight: "#D4C8E0",
      gold: "#E8D8B6",
      goldLight: "#D4C8A6",
      success: "#B8A9C9",
      muted: "#7A7088",
      border: "#4A4458",
      cardBackground: "#322D40",
      prayerActive: "#B8A9C9",
      prayerPast: "#7A7088",
    },
  },

  sagePeach: {
    id: "sagePeach",
    name: "Sage & Peach",
    nameAr: "أخضر وخوخي",
    description: "Nature-inspired soft tones",
    previewColors: ["#8FA68B", "#E6B8A2", "#FFFAF5"],
    light: {
      text: "#4A4A4A",
      textSecondary: "#7A7A7A",
      buttonText: "#FFFFFF",
      tabIconDefault: "#7A7A7A",
      tabIconSelected: "#8FA68B",
      link: "#8FA68B",
      backgroundRoot: "#FFFAF5",
      backgroundDefault: "#FFFFFF",
      backgroundSecondary: "#FFF5EB",
      backgroundTertiary: "#F5EBE0",
      primary: "#8FA68B",
      primaryLight: "#A6BFA2",
      gold: "#E6B8A2",
      goldLight: "#F5D4C4",
      success: "#8FA68B",
      muted: "#A0A0A0",
      border: "#F0E6DB",
      cardBackground: "#FFFFFF",
      prayerActive: "#8FA68B",
      prayerPast: "#A0A0A0",
    },
    dark: {
      text: "#F5F0EB",
      textSecondary: "#B8AFA5",
      buttonText: "#FFFFFF",
      tabIconDefault: "#7A7A7A",
      tabIconSelected: "#A6BFA2",
      link: "#A6BFA2",
      backgroundRoot: "#262420",
      backgroundDefault: "#332F2A",
      backgroundSecondary: "#403B35",
      backgroundTertiary: "#4D4840",
      primary: "#A6BFA2",
      primaryLight: "#C4D9C0",
      gold: "#F0C8B2",
      goldLight: "#E6B8A2",
      success: "#A6BFA2",
      muted: "#7A7A7A",
      border: "#4A4540",
      cardBackground: "#332F2A",
      prayerActive: "#A6BFA2",
      prayerPast: "#7A7A7A",
    },
  },

  oceanBreeze: {
    id: "oceanBreeze",
    name: "Ocean Breeze",
    nameAr: "نسيم البحر",
    description: "Serene blue tones",
    previewColors: ["#6B9DAD", "#C9B896", "#F5FAFB"],
    light: {
      text: "#3A4A50",
      textSecondary: "#6A7A80",
      buttonText: "#FFFFFF",
      tabIconDefault: "#6A7A80",
      tabIconSelected: "#6B9DAD",
      link: "#6B9DAD",
      backgroundRoot: "#F5FAFB",
      backgroundDefault: "#FFFFFF",
      backgroundSecondary: "#EBF5F7",
      backgroundTertiary: "#DCE8EB",
      primary: "#6B9DAD",
      primaryLight: "#8BB8C8",
      gold: "#C9B896",
      goldLight: "#E8DCC0",
      success: "#6B9DAD",
      muted: "#90A0A5",
      border: "#D4E8ED",
      cardBackground: "#FFFFFF",
      prayerActive: "#6B9DAD",
      prayerPast: "#90A0A5",
    },
    dark: {
      text: "#E8F0F2",
      textSecondary: "#A0B8C0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#6A7A80",
      tabIconSelected: "#8BB8C8",
      link: "#8BB8C8",
      backgroundRoot: "#1E2628",
      backgroundDefault: "#2A3538",
      backgroundSecondary: "#354245",
      backgroundTertiary: "#404D50",
      primary: "#8BB8C8",
      primaryLight: "#A8D0DE",
      gold: "#E8D8B6",
      goldLight: "#D4C8A6",
      success: "#8BB8C8",
      muted: "#6A7A80",
      border: "#3A4A50",
      cardBackground: "#2A3538",
      prayerActive: "#8BB8C8",
      prayerPast: "#6A7A80",
    },
  },
};

// Helper to get theme colors
export function getThemeColors(themeId: ThemeId, isDark: boolean): ThemeColors {
  const theme = Themes[themeId] || Themes.default;
  return isDark ? theme.dark : theme.light;
}

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  inputHeight: 48,
  buttonHeight: 52,
};

export const BorderRadius = {
  xs: 8,
  sm: 12,
  md: 18,
  lg: 24,
  xl: 30,
  "2xl": 40,
  "3xl": 50,
  full: 9999,
};


export const Typography = {
  h1: {
    fontSize: 28,
    fontWeight: "700" as const,
  },
  h2: {
    fontSize: 24,
    fontWeight: "700" as const,
  },
  h3: {
    fontSize: 20,
    fontWeight: "600" as const,
  },
  h4: {
    fontSize: 18,
    fontWeight: "600" as const,
  },
  body: {
    fontSize: 16,
    fontWeight: "400" as const,
  },
  bodyLarge: {
    fontSize: 18,
    fontWeight: "400" as const,
  },
  small: {
    fontSize: 14,
    fontWeight: "400" as const,
  },
  caption: {
    fontSize: 12,
    fontWeight: "400" as const,
  },
  arabic: {
    fontSize: 22,
    fontWeight: "400" as const,
  },
  arabicLarge: {
    fontSize: 28,
    fontWeight: "400" as const,
  },
  quran: {
    fontSize: 24,
    fontWeight: "400" as const,
  },
  link: {
    fontSize: 16,
    fontWeight: "400" as const,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
    arabic: "system-ui",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
    arabic: "normal",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    arabic: "'Noto Naskh Arabic', 'Traditional Arabic', 'Scheherazade', serif",
  },
});

export const Shadows = {
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardLight: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
};
